######################################################
#  SOURCE NAME: chkWindows.yml                       #
#  SOURCE TYPE: YAML FOR ANSIBLE                     #
#  PURPOSE: TO CHECK THE PREFERENCE                  #
#
#  REMARKS:                                          #
#  CONSTRUCTION:                                     #
#     hosts                                          #
#     chkWindow.yml                                  #
#     roles                                          #
#       |-chkIpAddress                               #
#           |-tasks                                  #
#               |-main.yml                           #
#       |-chkHostName                                #
#           |-tasks                                  #
#               |-main.yml                           #
#       |-chkService                                 #
#           |-tasks                                  #
#               |-main.yml                           #
#     library                                        #
#       |-Windows                                    #
#           |-chkIpAddress.ps1                       #
#           |-chkHostName.ps1                        #
#           |-chkService.ps1                         #
#       |-vCenter                                    #
#           |-chkPower.ps1                           #
#     files                                          #
#       |-parameter.yml                              #
#       |-chkLog.log                                 #
######################################################
---
- hosts: [chkWindows]
  user: tckknos
  serial: 1
  vars_files:
    - ./parameter.yml
  tasks:
    - chkVcenter:
        RES_OK="{{ RES_OK }}"
        RES_NG="{{ RES_NG }}"
        NO_ARG="{{ NO_ARG }}"
        SERVER_NAME="{{ SERVER_NAME }}"
        USER_NAME="{{ USER_NAME }}"
        PASS_WORD="{{ PASS_WORD }}"
        KEY="{{ item.KEY }}"
      with_items:
        - "{{ CHK_VCENTER }}"
